### ISSUE TITLE
After Entering main loop: Boost.Python.ArgumentError: 

### ISSUE THREAD

**Issue by sainisanjay** [FORTH-ModelBasedTracker/PyOpenPose#6]
```
Starting initialization on thread. In src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():44
Finished initialization on thread. In src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():67
Starting initialization on thread. In src/openpose/pose/poseRenderer.cpp:initializationOnThread():81
Finished initialization on thread. In src/openpose/pose/poseRenderer.cpp:initializationOnThread():88
Starting initialization on thread. In src/openpose/face/faceExtractor.cpp:initializationOnThread():37
Finished initialization on thread. In src/openpose/face/faceExtractor.cpp:initializationOnThread():58
Starting initialization on thread. In src/openpose/face/faceRenderer.cpp:initializationOnThread():39
Finished initialization on thread. In src/openpose/face/faceRenderer.cpp:initializationOnThread():45
Starting initialization on thread. In src/openpose/hand/handExtractor.cpp:initializationOnThread():122
Finished initialization on thread. In src/openpose/hand/handExtractor.cpp:initializationOnThread():143
Starting initialization on thread. In src/openpose/hand/handRenderer.cpp:initializationOnThread():40
Finished initialization on thread. In src/openpose/hand/handRenderer.cpp:initializationOnThread():46
Entering main Loop.
Traceback (most recent call last):
  File "OpLoop.py", line 84, in <module>
    run()
  File "OpLoop.py", line 50, in run
    op.detectPose(rgb)
Boost.Python.ArgumentError: Python argument types in
    OpenPose.detectPose(OpenPose, NoneType)
did not match C++ signature:
    detectPose(OpenPoseWrapper {lvalue}, cv::Mat)

```
I am using Ubuntu 14.04, Opencv 3.1.0 and Boost 1.64.

**Comment by padeler** [comment]
The image coming from the opencv capture is None. 

Maybe your web-cam is not working properly with opencv? Try loading an image from a file and giving that to detectPose.

**Comment by sainisanjay** [comment]
@padeler Thank you for your quick response. I am taking the input from video file only but the same error still occurs. Any other idea??
```
def run():   
    #cap = cv2.VideoCapture(0)
    cap = cv2.VideoCapture('video.avi')
```

**Comment by padeler** [comment]
Maybe the codec in the video is not supported by opencv? The simplest way to test openpose is to load an image. i.e. 

```python
img = cv2.imread("path/to/file/image.png")
```
Check the ipython notebook file in the [examples](https://github.com/FORTH-ModelBasedTracker/PyOpenPose/blob/master/scripts/optest.ipynb).

**Comment by sainisanjay** [comment]
Thanks @padeler. It works perfectly now.
